[package]
name = "anarchy_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = "0.4.0"
winit = "0.29.4"
anarchy_core = { path = "../anarchy_core" }
rand = "0.8.5"
ringbuf = "0.3.3"

