[package]
name = "anarchy_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anarchy_core = { path = "../anarchy_core" }
tikv-jemallocator = "0.5.4"
